# Site settings
title: Veibelysning i Vanvikbakkan
email: runar@hjerpbakk.com
description: > # this means to ignore newlines until "baseurl:"
  For Vanvikbakkan ligger det en teoretisk energibesparelse på ca.70%, med vegbelysning utført med LED og tilhørende smartstyring.
url: "https://veibelysning.github.io" # the base hostname & protocol for your site
production: true

# Build settings
markdown: kramdown

exclude:
  - Rakefile
  - favicon.pxm
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - tmp/
  - build.sh
  - clean.sh
  - jekyll.sh
  - preview.sh
  - publish.sh
  - purge.sh
  - test.sh
  - ci.sh
  - update.sh
  - view.sh
  - profile.sh
  - config.json
  - README.md
  - Responsive Image Breakpoints
  - cloudflare-cache-purger.csx
  - jekyll-share-script.csx
  - jekyll-yaml-front-matter-analyser.csx
  - .circleci/
  - .dockerignore
  - .frontmatterignore
  - .gitignore
  - .markdownlint.json
  - docker-compose.yml
  - sources/
  - LICENSE.txt